services:
  backend:
    build: .
    container_name: gv_backend
    ports:
      - "8000:8000"
      - "3000:3000"
    env_file:
      - .env
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: postgres:16-alpine3.20
    container_name: gv_db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  node_modules: