services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    develop:
      watch:
        - path: ./src
          target: /usr/src/app/src
          action: sync
        - path: ./package.json
          target: /usr/src/app/package.json
          action: sync

volumes:
  node_modules: